name: Snake Game
on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: vanessavpg
          outputs: |
            dist/github-snake.svg?color_snake=yellow&color_dots=blue&palette=github-dark

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
